# Generated by Django 5.1.1 on 2024-09-10 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_available_tickets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(default=True, related_name='events_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
